name: "Chromatic"

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history: https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code-and-above
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run prep-chromatic
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
