name: Storybook Build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: build
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
